replicaCount: 2

image:
  repository: ghcr.io/geotrif/ci-cd-template
  tag: "main"        # default; overridden by Image Updater OR manually
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}

ingress:
  enabled: false

autoscaling:
  enabled: false
